version: '3.9'

services:
  blue:
    image: celebrations-api:${IMAGE_VERSION-latest}
    ports:
      - 1336:1337
    environment:
      PROD_ADMIN_JWT_SECRET: ${PROD_ADMIN_JWT_SECRET}
      PROD_API_TOKEN_SALT: ${PROD_API_TOKEN_SALT}
      PROD_APP_KEYS: ${PROD_APP_KEYS}
      PROD_HOST: ${PROD_HOST}
      PROD_JWT_SECRET: ${PROD_JWT_SECRET}
      PROD_PORT: ${PROD_PORT}
      PROD_URL: ${PROD_URL}
      PROD_DATABASE_URL: ${PROD_DATABASE_URL}
      PROD_SMTP_HOST: ${PROD_SMTP_HOST}
      PROD_SMTP_PORT: ${PROD_SMTP_PORT}
      PROD_SMTP_USERNAME: ${PROD_SMTP_USERNAME}
      PROD_SMTP_PASSWORD: ${PROD_SMTP_PASSWORD}
  green:
    image: celebrations-api:${IMAGE_VERSION-latest}
    ports:
      - 1337:1337
    environment:
      PROD_ADMIN_JWT_SECRET: ${PROD_ADMIN_JWT_SECRET}
      PROD_API_TOKEN_SALT: ${PROD_API_TOKEN_SALT}
      PROD_APP_KEYS: ${PROD_APP_KEYS}
      PROD_HOST: ${PROD_HOST}
      PROD_JWT_SECRET: ${PROD_JWT_SECRET}
      PROD_PORT: ${PROD_PORT}
      PROD_URL: ${PROD_URL}
      PROD_DATABASE_URL: ${PROD_DATABASE_URL}
      PROD_SMTP_HOST: ${PROD_SMTP_HOST}
      PROD_SMTP_PORT: ${PROD_SMTP_PORT}
      PROD_SMTP_USERNAME: ${PROD_SMTP_USERNAME}
      PROD_SMTP_PASSWORD: ${PROD_SMTP_PASSWORD}
    restart: always
