name: Continuous Delivery

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: unnecessary
      - run: npm ci
      - run: npx pm2 deploy production setup
        env:
          SERVER_SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SERVER_SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
      - run: npx pm2 deploy production
        env:
          SERVER_SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SERVER_SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
          HOST: ${{ secrets.PROD_HOST }}
          PORT: ${{ secrets.PROD_PORT }}
          APP_KEYS: ${{ secrets.PROD_APP_KEYS }}
          API_TOKEN_SALT: ${{ secrets.PROD_API_TOKEN_SALT }}
          ADMIN_JWT_SECRET: ${{ secrets.PROD_ADMIN_JWT_SECRET }}
          JWT_SECRET: ${{ secrets.PROD_JWT_SECRET }}
