name: Continuous Delivery

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npx pm2 deploy production setup
        env:
          SERVER_SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SERVER_SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
      - run: SERVER_SSH_USER=$SERVER_SSH_USER SERVER_SSH_HOST=$SERVER_SSH_HOST npx pm2 deploy production
        env:
          SERVER_SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SERVER_SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
