name: CSV Generation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - uses: actions/checkout@v3
      - uses: githubocto/flat@v3
        with:
          sql_connstring: ${{ secrets.PROD_DATABASE_URL }}
          sql_queryfile: .github/scripts/csv.sql
          downloaded_filename: celebrations.csv
      - uses: actions/upload-artifact@v3
        with:
          name: celebrations
          path: celebrations.csv

