name: Health Check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Check the server URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.PROD_HOST }}:${{ secrets.PROD_PORT }}
