name: Health Check

on:
  schedule:
    - cron: '* * * * *'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Check the server URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.PROD_HOST }}:${{ secrets.PROD_PORT }}/_health
      - name: Telegram Notify
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Celebrations API

            Health Check failed.
