name: Celebrations Replication

on:
  schedule:
    - cron: '0 0 1 11 *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install --yes --no-install-recommends postgresql-client
          psql -Atx ${{ secrets.PROD_DATABASE_URL }} -c "$(cat .github/scripts/replicate.sql)"
