name: Replicate celebrations

on:
  schedule:
    - cron: '0 0 1 11 *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: azure/postgresql@v1
        with:
          connection-string: ${{ secrets.PROD_DATABASE_URL }}
          server-name: Server
          plsql-file: .github/scripts/replicate.sql
